### ISSUE TITLE
Get colour codes of fields

### ISSUE THREAD

**Issue by nfrankish** [py3270/py3270#14]
Im pretty new to the whole T3270 thing, but in our terminal emulators we show certain fields in certain colors for their status.

Im trying to determine how i would get the color of text in a position - is that even doable with this library or should i do some more reading about the protocol and extend it

**Comment by rsyring** [comment]
@nfrankish This library is a thin wrapper on top of the executables that are a part of [X3270](http://x3270.bgp.nu/).  If s3270 can do it, and you know the command to use with s3270, then py3270 can do it using `Emulator.exec_command()`.  HTH.
