### ISSUE TITLE
License

### ISSUE THREAD

**Issue by la-costa** [py3270/py3270#16]
Hi @rsyring 
I'm working on rearranging some parts of the repository.
A missing part is an explicit license.
I saw that in 'setup.py' you indicate BSD.
It has some variations, the most recommended in GitHub is MIT.
Which one do I add to the repository? MIT or BSD 2/3-clause?

**Comment by rsyring** [comment]
@la-costa Let's go with the 3-clause BSD.  Thanks for asking.

**Comment by la-costa** [comment]
License added in #17
