### ISSUE TITLE
[WinError 10061] when trying to connect.

### ISSUE THREAD

**Issue by Krogsager** [py3270/py3270#33]
Hi all, I'm trying to connect to an nt3270 terminal. I have no previous experience with these.
The code that fails looks like this:
```python
from py3270 import Emulator
em = Emulator(visible=True, args=["-port", "23"])
em.connect('172.31.190.138')
```

> [WinError 10061]  could not make a connection because the target machine actively refused it

I am, however, able to connect to the mainframe with telnet.
I can also connect by using another terminal emulator wc3270 by Paul Mattes https://x3270.miraheze.org/wiki/Main_Page
The code that fails is __init__.py, line 224, `sock.connect(("localhost", self.script_port))`

The system is Win10 64bit
Python 3.9.5.

**Comment by Krogsager** [comment]
Solved. I forgot to add the path to the emulators, so command line / cmd / Popen could not launch anything.
Add "C:\Program Files\wc3270\" to PATH.

**Comment by andres123456789883u249** [comment]
Hi, I am also working on a project for this. Which emulator did u download for windows 10?

**Comment by andres123456789883u249** [comment]
Also, did you just move the emulator to the folder with your files you are trying to run?

**Comment by Krogsager** [comment]
Hi @andres123456789883u249  (catchy name ;) ).
TL:DR  wc3270 https://x3270.miraheze.org/wiki/Downloads

It is right there in my original post:  [wc3270 by Paul Mattes](http://x3270.bgp.nu/). The link to the emulator is also in the README for this repo.

I did not move the emulator, rather I let it install in its default path on windows. [Then add the .exe path to PATH. ](https://github.com/py3270/py3270/blob/5e625383406fb546c978a0343b63ba138b100b54/README.rst#example)
I missed it in the readme at first. Hence this issue.
![image](https://user-images.githubusercontent.com/27994384/177711772-ddd72c61-45f8-4634-9697-bac4bfb9f866.png)

**Comment by andres123456789883u249** [comment]
Thank you for responding! The link you sent for the emulator, has a variety of versions, is there one you recommend?

**Comment by andres123456789883u249** [comment]
Also, did u have to ever run anything? or just download the emulator
